deploy: 088ba7450b3ad4894b7060711fa7cd89b615805b

diff --git a/target/_private/executable/ingestion_qc/h5mu_to_qc_json/h5mu_to_qc_json b/target/_private/executable/ingestion_qc/h5mu_to_qc_json/h5mu_to_qc_json
--- a/target/_private/executable/ingestion_qc/h5mu_to_qc_json/h5mu_to_qc_json
+++ b/target/_private/executable/ingestion_qc/h5mu_to_qc_json/h5mu_to_qc_json
@@ -461,9 +461,9 @@ RUN pip install --upgrade pip && \
 
 LABEL org.opencontainers.image.authors="Jakub Majercik, Dorien Roosen, Robrecht Cannoodt, Weiwei Schultz"
 LABEL org.opencontainers.image.description="Companion container for running component ingestion_qc h5mu_to_qc_json"
-LABEL org.opencontainers.image.created="2026-02-02T15:57:51Z"
+LABEL org.opencontainers.image.created="2026-02-02T16:21:01Z"
 LABEL org.opencontainers.image.source="https://github.com/openpipelines-bio/openpipeline_qc"
-LABEL org.opencontainers.image.revision="791ad93f82f1e5ace3c6505d80d4cb9c37a89d30"
+LABEL org.opencontainers.image.revision="088ba7450b3ad4894b7060711fa7cd89b615805b"
 LABEL org.opencontainers.image.version="build_main"
 
 VIASHDOCKER
@@ -601,7 +601,7 @@ function ViashHelp {
   echo ""
   echo "    --ingestion_method"
   echo "        type: string, required parameter"
-  echo "        choices: [ cellranger_multi, xenium, visium ]"
+  echo "        choices: [ cellranger_multi, xenium, cosmx, visium ]"
   echo "        Method that was used to ingest the data - this will define the structure"
   echo "        of the report that is generated."
   echo ""
@@ -704,6 +704,43 @@ function ViashHelp {
   echo "        default: control_codeword_counts"
   echo "        The key in the h5mu .obs field that contains the number of control"
   echo "        codewords."
+  echo ""
+  echo "Options for CosMx reports:"
+  echo "    --obs_area"
+  echo "        type: string"
+  echo "        default: Area"
+  echo "        The key in the h5mu .obs field that contains the cell area."
+  echo ""
+  echo "    --obs_aspect_ratio"
+  echo "        type: string"
+  echo "        default: AspectRatio"
+  echo "        The key in the h5mu .obs field that contains the aspect ratio."
+  echo ""
+  echo "    --obs_dapi_stain"
+  echo "        type: string, multiple values allowed"
+  echo "        default: Mean.DAPI;Max.DAPI"
+  echo "        The keys in the h5mu .obs field that contains the DAPI stain intensity."
+  echo ""
+  echo "    --obs_membrane_stain"
+  echo "        type: string, multiple values allowed"
+  echo "        default: Mean.MembraneStain;Max.MembraneStain"
+  echo "        The keys in the h5mu .obs field that contains the membrane stain"
+  echo "        intensity."
+  echo ""
+  echo "    --obs_panck_stain"
+  echo "        type: string, multiple values allowed"
+  echo "        default: Mean.PanCK;Max.PanCK"
+  echo "        The keys in the h5mu .obs field that contains the PanCK stain intensity."
+  echo ""
+  echo "    --obs_cd45_stain"
+  echo "        type: string, multiple values allowed"
+  echo "        default: Mean.CD45;Max.CD45"
+  echo "        The keys in the h5mu .obs field that contains the CD45 stain intensity."
+  echo ""
+  echo "    --obs_cd3_stain"
+  echo "        type: string, multiple values allowed"
+  echo "        default: Mean.CD3;Max.CD3"
+  echo "        The keys in the h5mu .obs field that contains the CD3 stain intensity."
   echo ""
   echo "Viash built in Computational Requirements:"
   echo "    ---cpus=INT"
@@ -1004,6 +1041,113 @@ while [[ $# -gt 0 ]]; do
             VIASH_PAR_OBS_CONTROL_CODEWORD_COUNTS=$(ViashRemoveFlags "$1")
             shift 1
             ;;
+        --obs_area)
+            [ -n "$VIASH_PAR_OBS_AREA" ] && ViashError Bad arguments for option \'--obs_area\': \'$VIASH_PAR_OBS_AREA\' \& \'$2\' - you should provide exactly one argument for this option. && exit 1
+            VIASH_PAR_OBS_AREA="$2"
+            [ $# -lt 2 ] && ViashError Not enough arguments passed to --obs_area. Use "--help" to get more information on the parameters. && exit 1
+            shift 2
+            ;;
+        --obs_area=*)
+            [ -n "$VIASH_PAR_OBS_AREA" ] && ViashError Bad arguments for option \'--obs_area=*\': \'$VIASH_PAR_OBS_AREA\' \& \'$2\' - you should provide exactly one argument for this option. && exit 1
+            VIASH_PAR_OBS_AREA=$(ViashRemoveFlags "$1")
+            shift 1
+            ;;
+        --obs_aspect_ratio)
+            [ -n "$VIASH_PAR_OBS_ASPECT_RATIO" ] && ViashError Bad arguments for option \'--obs_aspect_ratio\': \'$VIASH_PAR_OBS_ASPECT_RATIO\' \& \'$2\' - you should provide exactly one argument for this option. && exit 1
+            VIASH_PAR_OBS_ASPECT_RATIO="$2"
+            [ $# -lt 2 ] && ViashError Not enough arguments passed to --obs_aspect_ratio. Use "--help" to get more information on the parameters. && exit 1
+            shift 2
+            ;;
+        --obs_aspect_ratio=*)
+            [ -n "$VIASH_PAR_OBS_ASPECT_RATIO" ] && ViashError Bad arguments for option \'--obs_aspect_ratio=*\': \'$VIASH_PAR_OBS_ASPECT_RATIO\' \& \'$2\' - you should provide exactly one argument for this option. && exit 1
+            VIASH_PAR_OBS_ASPECT_RATIO=$(ViashRemoveFlags "$1")
+            shift 1
+            ;;
+        --obs_dapi_stain)
+            if [ -z "$VIASH_PAR_OBS_DAPI_STAIN" ]; then
+              VIASH_PAR_OBS_DAPI_STAIN="$2"
+            else
+              VIASH_PAR_OBS_DAPI_STAIN="$VIASH_PAR_OBS_DAPI_STAIN;""$2"
+            fi
+            [ $# -lt 2 ] && ViashError Not enough arguments passed to --obs_dapi_stain. Use "--help" to get more information on the parameters. && exit 1
+            shift 2
+            ;;
+        --obs_dapi_stain=*)
+            if [ -z "$VIASH_PAR_OBS_DAPI_STAIN" ]; then
+              VIASH_PAR_OBS_DAPI_STAIN=$(ViashRemoveFlags "$1")
+            else
+              VIASH_PAR_OBS_DAPI_STAIN="$VIASH_PAR_OBS_DAPI_STAIN;"$(ViashRemoveFlags "$1")
+            fi
+            shift 1
+            ;;
+        --obs_membrane_stain)
+            if [ -z "$VIASH_PAR_OBS_MEMBRANE_STAIN" ]; then
+              VIASH_PAR_OBS_MEMBRANE_STAIN="$2"
+            else
+              VIASH_PAR_OBS_MEMBRANE_STAIN="$VIASH_PAR_OBS_MEMBRANE_STAIN;""$2"
+            fi
+            [ $# -lt 2 ] && ViashError Not enough arguments passed to --obs_membrane_stain. Use "--help" to get more information on the parameters. && exit 1
+            shift 2
+            ;;
+        --obs_membrane_stain=*)
+            if [ -z "$VIASH_PAR_OBS_MEMBRANE_STAIN" ]; then
+              VIASH_PAR_OBS_MEMBRANE_STAIN=$(ViashRemoveFlags "$1")
+            else
+              VIASH_PAR_OBS_MEMBRANE_STAIN="$VIASH_PAR_OBS_MEMBRANE_STAIN;"$(ViashRemoveFlags "$1")
+            fi
+            shift 1
+            ;;
+        --obs_panck_stain)
+            if [ -z "$VIASH_PAR_OBS_PANCK_STAIN" ]; then
+              VIASH_PAR_OBS_PANCK_STAIN="$2"
+            else
+              VIASH_PAR_OBS_PANCK_STAIN="$VIASH_PAR_OBS_PANCK_STAIN;""$2"
+            fi
+            [ $# -lt 2 ] && ViashError Not enough arguments passed to --obs_panck_stain. Use "--help" to get more information on the parameters. && exit 1
+            shift 2
+            ;;
+        --obs_panck_stain=*)
+            if [ -z "$VIASH_PAR_OBS_PANCK_STAIN" ]; then
+              VIASH_PAR_OBS_PANCK_STAIN=$(ViashRemoveFlags "$1")
+            else
+              VIASH_PAR_OBS_PANCK_STAIN="$VIASH_PAR_OBS_PANCK_STAIN;"$(ViashRemoveFlags "$1")
+            fi
+            shift 1
+            ;;
+        --obs_cd45_stain)
+            if [ -z "$VIASH_PAR_OBS_CD45_STAIN" ]; then
+              VIASH_PAR_OBS_CD45_STAIN="$2"
+            else
+              VIASH_PAR_OBS_CD45_STAIN="$VIASH_PAR_OBS_CD45_STAIN;""$2"
+            fi
+            [ $# -lt 2 ] && ViashError Not enough arguments passed to --obs_cd45_stain. Use "--help" to get more information on the parameters. && exit 1
+            shift 2
+            ;;
+        --obs_cd45_stain=*)
+            if [ -z "$VIASH_PAR_OBS_CD45_STAIN" ]; then
+              VIASH_PAR_OBS_CD45_STAIN=$(ViashRemoveFlags "$1")
+            else
+              VIASH_PAR_OBS_CD45_STAIN="$VIASH_PAR_OBS_CD45_STAIN;"$(ViashRemoveFlags "$1")
+            fi
+            shift 1
+            ;;
+        --obs_cd3_stain)
+            if [ -z "$VIASH_PAR_OBS_CD3_STAIN" ]; then
+              VIASH_PAR_OBS_CD3_STAIN="$2"
+            else
+              VIASH_PAR_OBS_CD3_STAIN="$VIASH_PAR_OBS_CD3_STAIN;""$2"
+            fi
+            [ $# -lt 2 ] && ViashError Not enough arguments passed to --obs_cd3_stain. Use "--help" to get more information on the parameters. && exit 1
+            shift 2
+            ;;
+        --obs_cd3_stain=*)
+            if [ -z "$VIASH_PAR_OBS_CD3_STAIN" ]; then
+              VIASH_PAR_OBS_CD3_STAIN=$(ViashRemoveFlags "$1")
+            else
+              VIASH_PAR_OBS_CD3_STAIN="$VIASH_PAR_OBS_CD3_STAIN;"$(ViashRemoveFlags "$1")
+            fi
+            shift 1
+            ;;
         ---engine)
             VIASH_ENGINE_ID="$2"
             shift 2
@@ -1264,6 +1408,27 @@ fi
 if [ -z ${VIASH_PAR_OBS_CONTROL_CODEWORD_COUNTS+x} ]; then
   VIASH_PAR_OBS_CONTROL_CODEWORD_COUNTS="control_codeword_counts"
 fi
+if [ -z ${VIASH_PAR_OBS_AREA+x} ]; then
+  VIASH_PAR_OBS_AREA="Area"
+fi
+if [ -z ${VIASH_PAR_OBS_ASPECT_RATIO+x} ]; then
+  VIASH_PAR_OBS_ASPECT_RATIO="AspectRatio"
+fi
+if [ -z ${VIASH_PAR_OBS_DAPI_STAIN+x} ]; then
+  VIASH_PAR_OBS_DAPI_STAIN="Mean.DAPI;Max.DAPI"
+fi
+if [ -z ${VIASH_PAR_OBS_MEMBRANE_STAIN+x} ]; then
+  VIASH_PAR_OBS_MEMBRANE_STAIN="Mean.MembraneStain;Max.MembraneStain"
+fi
+if [ -z ${VIASH_PAR_OBS_PANCK_STAIN+x} ]; then
+  VIASH_PAR_OBS_PANCK_STAIN="Mean.PanCK;Max.PanCK"
+fi
+if [ -z ${VIASH_PAR_OBS_CD45_STAIN+x} ]; then
+  VIASH_PAR_OBS_CD45_STAIN="Mean.CD45;Max.CD45"
+fi
+if [ -z ${VIASH_PAR_OBS_CD3_STAIN+x} ]; then
+  VIASH_PAR_OBS_CD3_STAIN="Mean.CD3;Max.CD3"
+fi
 
 # check whether required files exist
 if [ ! -z "$VIASH_PAR_INPUT" ]; then
@@ -1367,7 +1532,7 @@ fi
 
 # check whether value is belongs to a set of choices
 if [ ! -z "$VIASH_PAR_INGESTION_METHOD" ]; then
-  VIASH_PAR_INGESTION_METHOD_CHOICES=("cellranger_multi;xenium;visium")
+  VIASH_PAR_INGESTION_METHOD_CHOICES=("cellranger_multi;xenium;cosmx;visium")
   IFS=';'
   set -f
   if ! [[ ";${VIASH_PAR_INGESTION_METHOD_CHOICES[*]};" =~ ";$VIASH_PAR_INGESTION_METHOD;" ]]; then
@@ -1509,7 +1674,14 @@ par = {
   'obs_x_coord': $( if [ ! -z ${VIASH_PAR_OBS_X_COORD+x} ]; then echo "r'${VIASH_PAR_OBS_X_COORD//\'/\'\"\'\"r\'}'"; else echo None; fi ),
   'obs_y_coord': $( if [ ! -z ${VIASH_PAR_OBS_Y_COORD+x} ]; then echo "r'${VIASH_PAR_OBS_Y_COORD//\'/\'\"\'\"r\'}'"; else echo None; fi ),
   'obs_control_probe_counts': $( if [ ! -z ${VIASH_PAR_OBS_CONTROL_PROBE_COUNTS+x} ]; then echo "r'${VIASH_PAR_OBS_CONTROL_PROBE_COUNTS//\'/\'\"\'\"r\'}'"; else echo None; fi ),
-  'obs_control_codeword_counts': $( if [ ! -z ${VIASH_PAR_OBS_CONTROL_CODEWORD_COUNTS+x} ]; then echo "r'${VIASH_PAR_OBS_CONTROL_CODEWORD_COUNTS//\'/\'\"\'\"r\'}'"; else echo None; fi )
+  'obs_control_codeword_counts': $( if [ ! -z ${VIASH_PAR_OBS_CONTROL_CODEWORD_COUNTS+x} ]; then echo "r'${VIASH_PAR_OBS_CONTROL_CODEWORD_COUNTS//\'/\'\"\'\"r\'}'"; else echo None; fi ),
+  'obs_area': $( if [ ! -z ${VIASH_PAR_OBS_AREA+x} ]; then echo "r'${VIASH_PAR_OBS_AREA//\'/\'\"\'\"r\'}'"; else echo None; fi ),
+  'obs_aspect_ratio': $( if [ ! -z ${VIASH_PAR_OBS_ASPECT_RATIO+x} ]; then echo "r'${VIASH_PAR_OBS_ASPECT_RATIO//\'/\'\"\'\"r\'}'"; else echo None; fi ),
+  'obs_dapi_stain': $( if [ ! -z ${VIASH_PAR_OBS_DAPI_STAIN+x} ]; then echo "r'${VIASH_PAR_OBS_DAPI_STAIN//\'/\'\"\'\"r\'}'.split(';')"; else echo None; fi ),
+  'obs_membrane_stain': $( if [ ! -z ${VIASH_PAR_OBS_MEMBRANE_STAIN+x} ]; then echo "r'${VIASH_PAR_OBS_MEMBRANE_STAIN//\'/\'\"\'\"r\'}'.split(';')"; else echo None; fi ),
+  'obs_panck_stain': $( if [ ! -z ${VIASH_PAR_OBS_PANCK_STAIN+x} ]; then echo "r'${VIASH_PAR_OBS_PANCK_STAIN//\'/\'\"\'\"r\'}'.split(';')"; else echo None; fi ),
+  'obs_cd45_stain': $( if [ ! -z ${VIASH_PAR_OBS_CD45_STAIN+x} ]; then echo "r'${VIASH_PAR_OBS_CD45_STAIN//\'/\'\"\'\"r\'}'.split(';')"; else echo None; fi ),
+  'obs_cd3_stain': $( if [ ! -z ${VIASH_PAR_OBS_CD3_STAIN+x} ]; then echo "r'${VIASH_PAR_OBS_CD3_STAIN//\'/\'\"\'\"r\'}'.split(';')"; else echo None; fi )
 }
 meta = {
   'name': $( if [ ! -z ${VIASH_META_NAME+x} ]; then echo "r'${VIASH_META_NAME//\'/\'\"\'\"r\'}'"; else echo None; fi ),
@@ -1543,6 +1715,11 @@ from setup_logger import setup_logger
 logger = setup_logger()
 
 par["obs_cellbender"] = {} if not par["obs_cellbender"] else par["obs_cellbender"]
+par["obs_dapi_stain"] = [] if not par["obs_dapi_stain"] else par["obs_dapi_stain"]
+par["obs_membrane_stain"] = [] if not par["obs_membrane_stain"] else par["obs_membrane_stain"]
+par["obs_panck_stain"] = [] if not par["obs_panck_stain"] else par["obs_panck_stain"]
+par["obs_cd45_stain"] = [] if not par["obs_cd45_stain"] else par["obs_cd45_stain"]
+par["obs_cd3_stain"] = [] if not par["obs_cd3_stain"] else par["obs_cd3_stain"]
 
 
 def transform_df(df):
@@ -1759,6 +1936,60 @@ def generate_visium_stats(mod_obs, sample_id, required_keys):
     return cell_rna_stats
 
 
+def format_cosmx_columns(mod_obs):
+
+    cosmx_obs_keys = [par["obs_area"], par["obs_aspect_ratio"]]
+    
+    # Add multiple keys
+    for key_list in [par["obs_dapi_stain"], par["obs_membrane_stain"], par["obs_panck_stain"],
+                     par["obs_cd45_stain"], par["obs_cd3_stain"]]:
+                     if key_list:
+                         cosmx_obs_keys.extend(key_list)
+                     
+    # Check if keys are present
+    check_optional_obs_keys(mod_obs, cosmx_obs_keys, "CosMx metrics.")
+    
+    # Filter only existing keys
+    cosmx_formatted_columns = [key for key in cosmx_obs_keys if key in mod_obs]
+    
+    # Add coordinates
+    cosmx_formatted_columns.extend(["x_coord", "y_coord"])
+    
+    for key in cosmx_formatted_columns:
+        if key in mod_obs:
+            if not pd.api.types.is_float_dtype(mod_obs[key]):
+                try:
+                    mod_obs[key] = mod_obs[key].astype("float16")
+                except ValueError:
+                    logger.warning(f"Could not convert column {key} to a float dtype.")
+
+    return mod_obs, cosmx_formatted_columns
+
+
+def generate_cosmx_stats(mod_obs, sample_id, required_keys):
+    
+    # Format required columns
+    mod_obs = format_required_columns(required_keys, mod_obs)
+
+    # Format cosmx-specific columns
+    mod_obs, cosmx_formatted_columns = format_cosmx_columns(mod_obs)
+
+    # Fetch and format  all categorical columns for grouping
+    metadata_obs_keys, mod_obs = format_categorical_columns(mod_obs)
+
+    # Create cell RNA stats dataframe
+    cell_rna_stats = pd.DataFrame(
+        {
+            "sample_id": pd.Categorical(sample_id),
+            **{key: mod_obs[key] for key in required_keys},
+            **{key: mod_obs[key] for key in cosmx_formatted_columns},
+            **{key: mod_obs[key] for key in metadata_obs_keys}
+        }
+    )
+
+    return cell_rna_stats
+
+
 def concatenate_dataframes(dfs):
     '''Concatenates a list of dataframes into a single dataframe, preserving categorical columns.'''
     df = pd.concat(dfs, ignore_index=True)
@@ -1798,7 +2029,7 @@ def main(par):
         barcodes_original_count = mod_obs.shape[0]
 
         # Add coordinates to obs before filtering
-        if par["ingestion_method"] == "xenium" or par["ingestion_method"] == "visium":
+        if par["ingestion_method"] == "xenium" or par["ingestion_method"] == "visium" or par["ingestion_method"] == "cosmx":
             mod_obs["x_coord"] = mod_obsm["spatial"][:, 0]
             mod_obs["y_coord"] = mod_obsm["spatial"][:, 1]
 
@@ -1855,6 +2086,9 @@ def main(par):
         
         if par["ingestion_method"] == "visium":
             cell_rna_stats = generate_visium_stats(mod_obs, sample_id, required_keys)
+        
+        if par["ingestion_method"] == "cosmx":
+            cell_rna_stats = generate_cosmx_stats(mod_obs, sample_id, required_keys)
 
         cell_stats_dfs.append(cell_rna_stats)
         sample_stats_dfs.append(sample_summary_stats)
@@ -1890,7 +2124,8 @@ def main(par):
     report_structures = {
         "cellranger_multi": os.path.join(meta["resources_dir"], "report_structure/cellranger.json"),
         "xenium": os.path.join(meta["resources_dir"], "report_structure/xenium.json"),
-        "visium": os.path.join(meta["resources_dir"], "report_structure/visium.json")
+        "visium": os.path.join(meta["resources_dir"], "report_structure/visium.json"),
+        "cosmx": os.path.join(meta["resources_dir"], "report_structure/cosmx.json")
     }
 
     logger.info(f"Writing output report structure json to {par['output_reporting_json']}")
